CREATE DATABASE eletrodomestico_saep_db;
USE eletrodomestico_saep_db;


CREATE TABLE USUARIO (
    USU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(255),
    USU_EMAIL VARCHAR(255) UNIQUE,
    USU_SENHA VARCHAR(255)
);

CREATE TABLE PRODUTOS (
    PRODUTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    PRODUTO_NOME VARCHAR(255),
    PRODUTO_FORNECEDOR VARCHAR(255),
    PRODUTO_CATEGORIA VARCHAR(255),
    PRODUTO_POTENCIA VARCHAR(255),
    PRODUTO_CONSUMO VARCHAR(255),
    PRODUTO_GARANTIA VARCHAR(255),
    PRODUTO_PRIORIDADE VARCHAR(255),
    FK_USU_ID INTEGER
);

CREATE TABLE ESTOQUE (
    ESTOQUE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ESTOQUE_QUANTIDADE INTEGER,
    FK_PRODUTO_ID INTEGER
);

CREATE TABLE LOGS (
    LOG_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LOG_DESCRICAO VARCHAR(255),
    LOG_DATA_HORA DATE
);
 
ALTER TABLE PRODUTOS ADD CONSTRAINT FK_PRODUTOS_2
    FOREIGN KEY (FK_USU_ID)
    REFERENCES USUARIO (USU_ID);
 
ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_2
    FOREIGN KEY (FK_PRODUTO_ID)
    REFERENCES PRODUTOS (PRODUTO_ID);

CREATE DATABASE eletrodomestico_saep_db;
USE eletrodomestico_saep_db;

INSERT INTO USUARIO (USU_NOME, USU_EMAIL, USU_SENHA) VALUES
('Maria Oliveira', 'maria.oliveira@email.com', '123456'),
('João Santos', 'joao.santos@email.com', '123456'),
('Carla Mendes', 'carla.mendes@email.com', '123456');

INSERT INTO PRODUTOS (PRODUTO_NOME, PRODUTO_FORNECEDOR, PRODUTO_CATEGORIA, PRODUTO_POTENCIA, PRODUTO_CONSUMO, PRODUTO_GARANTIA, PRODUTO_PRIORIDADE, FK_USU_ID) VALUES
('Geladeira Frost Free 400L', 'EletroPlus', 'Refrigeração', '1200W', '45 kWh/mês', '12 meses', 'Alta', 1),
('Micro-ondas 30L', 'CozinhaTech', 'Cozinha', '800W', '15 kWh/mês', '6 meses', 'Média', 2),
('Máquina de Lavar 11kg', 'CleanHome', 'Lavanderia', '1500W', '60 kWh/mês', '24 meses', 'Alta', 3);

INSERT INTO ESTOQUE (ESTOQUE_QUANTIDADE, FK_PRODUTO_ID) VALUES
(20, 1),
(35, 2),
(15, 3);
    